apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: multi-platform-controller-example-test
spec:
  description: |-
    Here be an example integration test Pipeline
  params: 
  tasks:  
  finally:
